version: "3.9"

services:

  node:
    build:
      args:
        user: nodeuser
        uid: 1001
      context: ./.docker/node
    volumes:
      - ./:/application
    ports:
      - 1234:1234
      - 9229:9229
    container_name: lisaraelc-node
    tty: true
