version: "3.7"

services:

  node:
    build:
      args:
        user: nodeuser
        uid: 1001
      context: ./.docker/node
    volumes:
      [.:/app]
    ports:
      [1234:1234]
    container_name: lisaraelc-node
    tty: true
